---
galaxy_info:
  author: Moise Kameni
  description: Installs firewalld
  license: "license (BSD, MIT)"
  min_ansible_version: 1.8
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags: []

dependencies: []
