---
dependencies: []

galaxy_info:
  author: Moise Kameni
  description: Nginx installation for Linux.
  company: "Adaware"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.8
  platforms:
    - name: EL
      versions:
      - 6
      - 7
  galaxy_tags:
    - development
    - web
    - nginx
