---
nginx_install_service: True
nginx_user: 'nginx'
nginx_worker_processes: '{{ ansible_processor_vcpus | default(ansible_processor_count) }}'
nginx_error_log: '/var/log/nginx/error.log'
nginx_pid_file: '/var/run/nginx.pid'

nginx_events_worker_connections: 1024
nginx_events_multi_accept: 'off'

nginx_server_tokens: 'off'
nginx_mine_types: '/etc/nginx/mime.types'
nginx_default_type: 'application/octet-stream'
nginx_charset_types: 'text/css text/plain text/vnd.wap.wml application/javascript application/json application/rss+xml application/xml'
nginx_access_log:  '/var/log/nginx/access.log  main'
nginx_sendfile: 'on'
nginx_tcp_nopush: 'off'
nginx_tcp_nodelay: 'on'
nginx_keepalive_timeout: '65'
nginx_keepalive_requests: '100'
nginx_gzip: 'off'
nginx_variables_hash_max_size: '1024'
nginx_variables_hash_bucket_size: '64'
nginx_server_names_hash_bucket_size: '64'
nginx_types_hash_max_size: '2048'
nginx_types_hash_bucket_size: '64'
nginx_client_max_body_size: '128m'
nginx_http_log_format: |
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'

nginx_proxy_cache_path: ""

#nginx_config_dir_default: '/etc/nginx/conf.d/*.conf'
#nginx_config_dir: '/etc/nginx/sites-enabled/*.conf'
nginx_conf_file_path: '/etc/nginx/nginx.conf'
nginx_config_dir_default: '/etc/nginx/conf.d'
nginx_default_vhost_path: '/etc/nginx/conf.d/default.conf'
nginx_sites_available_dir: '/etc/nginx/sites-available'
nginx_sites_enabled_dir: '/etc/nginx/sites-enabled'
nginx_log_dir: '/var/log/nginx'
